{% set version = "3.4.11" %}

package:
  name: dictionaryutils
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dictionaryutils/dictionaryutils-{{ version }}.tar.gz
  sha256: a63ae34b4c0130cd94e4ca685cbb18155c225f9bface32ed1d503393d0dd39cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - jsonschema >=2.5,<4
    - cdislogging
    - requests

test:
  commands:
    - pip check
  imports:
    - dictionaryutils
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/dictionaryutils
  summary: Python wrapper and metaschema for datadictionary.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
