schema_version: 1

context:
  version: "4.0.0"
  python_min: 3.13

package:
  name: dictionaryutils
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dictionaryutils/dictionaryutils-${{ version }}.tar.gz
  sha256: c846c48d534c7ae4a47d65b29cb7bb4324e998366e81ff5cc2175c94b1ea0c77

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml
    - jsonschema >=2.5,<4
    - cdislogging
    - requests

tests:
  - python:
      imports:
        - dictionaryutils
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Python wrapper and metaschema for datadictionary.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/uc-cdis/dictionaryutils

extra:
  recipe-maintainers:
    - danielnachun
